---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-crb
subjects:
  - kind: ServiceAccount
    name: event-sa
    namespace: global
roleRef:
  kind: ClusterRole
  name: saas-user-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-sa
  namespace: global
  labels:
    addonmanager.kubernetes.io/mode: Reconcile